#!/usr/bin/python3
# -*- coding utf-8 -*-

import sys
from ezblock import run_command, Pin
import time

def service_status():
    status = sys.argv[1]
    mcurst = Pin("MCURST")
    filename = '/opt/ezblock/main.py'
    if status == "start":
        mcurst.on()
        _, data = run_command("ls /opt/ezblock")
        if "main.py" in data:
            run_command("python3 /opt/ezblock/main.py &")
    elif status == "stop":
        run_command("sudo kill $(ps aux | grep -m 1 '%s' | awk '{ print $2 }')" % (filename))
        mcurst.off()
        time.sleep(0.001)
        

service_status()
    